apiVersion: v1
kind: Service
metadata:
  name: {{ include "front-webui.fullname" . }}
  labels:
    {{- include "front-webui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "front-webui.selectorLabels" . | nindent 4 }}


### include "front-webui 이름 드래그 -> 모두 변경 후 chart의 name으로 변경 
