apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/azure-disk
    volumehelper.VolumeDynamicallyCreatedByKey: azure-disk-dynamic-provisioner
  creationTimestamp: "2021-11-09T07:17:03Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    failure-domain.beta.kubernetes.io/region: koreacentral
  name: pvc-1399f299-7013-4fc9-80d3-949ea45a1828
spec:
  accessModes:
  - ReadWriteOnce
  azureDisk:
    cachingMode: ReadOnly
    diskName: kubernetes-dynamic-pvc-1399f299-7013-4fc9-80d3-949ea45a1828
    diskURI: /subscriptions/d5ee09b5-8400-434f-bc01-edda13c28514/resourceGroups/mc_skr-evpark-d-rg_skr-evpark-d-aks_koreacentral/providers/Microsoft.Compute/disks/kubernetes-dynamic-pvc-1399f299-7013-4fc9-80d3-949ea45a1828
    fsType: ""
    kind: Managed
    readOnly: false
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: alertmanager-prometheus-prometheus-oper-alertmanager-db-alertmanager-prometheus-prometheus-oper-alertmanager-0
    namespace: monitoring
    resourceVersion: "2089423"
    uid: 1399f299-7013-4fc9-80d3-949ea45a1828
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/region
          operator: In
          values:
          - koreacentral
  persistentVolumeReclaimPolicy: Delete
  storageClassName: default
  volumeMode: Filesystem
status:
  phase: Bound
